### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by niftyapple** [CodeCrafter47/GlobalTablist#1]
I have found that GlobalTabList is incompatible with LibsDisguises when morphing into another player, only when using GTL. When morphed, you go invisible. I have thoroughly tested and can recreate this issue just by removing or adding GTL to the plugins list. 

Are you aware of this incompatibility? Also does your other plugin, BungeeTabList create these same issues?

**Comment by NavidK0** [comment]
This issue hasn't been present for quite some time now. I don't remember the commit that fixed it, but I do believe I mentioned that it was fixed in an update post on LibsDisguises. In fact, I use GlobalTablist on my network currently, and it works just fine.
