### ISSUE TITLE
Global tablist mode not working in current BungeeCord version

### ISSUE THREAD

**Issue by Black-Hole** [CodeCrafter47/GlobalTablist#2]
After this commit https://github.com/SpigotMC/BungeeCord/commit/06ad0f9310c0874494cd5bef870399cb6146bfd1 players could only see other players from their current server. If the commit is reverted it's working again perfectly.

**Comment by helptiger** [comment]
same issue too

**Comment by Black-Hole** [comment]
Thanks for the quick fix. :+1:
