### ISSUE TITLE
Misbehaving when reconnecting

### ISSUE THREAD

**Issue by Jckf** [CodeCrafter47/GlobalTablist#3]
When two Minecraft clients connect with the same account, GlobalTabList no longer shows the player. Presumably because the events are fired in the following order, causing the disconnect event to remove the player from the list, although a second session is still active:

First client connects.
Second client connects.
First client disconnects.

**Comment by CodeCrafter47** [comment]
The issue also occurs without this plugin.

**Comment by Jckf** [comment]
Really? So Bungee itself handles its own events incorrectly? That's interesting. GlobalTablist could fix it though, I assume?

**Comment by Jckf** [comment]
After updating to this snapshot, the player count shown in the server list is incorrect. Looks like it remembers players that are kicked, causing the number to be higher than it should be. It's currently showing 42 players that are nowhere to be found, but the tab list itself does not show them.

**Comment by CodeCrafter47** [comment]
Somehow I can't reproduce that.

**Comment by Jckf** [comment]
Enable whitelist on the server, and don't add yourself. Try to connect through a BungeeCord running this plugin. Get kicked. The player count should now show 1, even though you were kicked.

**Comment by CodeCrafter47** [comment]
I figured it out.

**Comment by Jckf** [comment]
Both problems seem to be resolved.

**Comment by CodeCrafter47** [comment]
Still happens if useGlobalTablist is set to false in config. Not sure if I should fix that.

**Comment by Jckf** [comment]
I don't think that's for this plugin to do. The problem should be reported to, and fixed in BungeeCord.
